site_name: NPBlender
site_description: "NumPy-based geometry for Blender"
site_author: "Alain Bernard"
repo_url: https://github.com/al1brn/npblender

theme:
  name: material
  language: fr
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - content.code.copy

nav:
  - Accueil: index.md
  #- Installation: installation.md
  #- Utilisation:
  #    - Aperçu: usage/index.md
  #    - Maths: usage/maths.md
  #    - Blender: usage/blender.md
  - Référence API:
      - npblender: api/index.md
      - Mesh: api/mesh.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            #docstring_style: google   # ou sphinx, selon ton style
            docstring_style: numpy             
            docstring_section_style: table     # sections (Arguments, Returns, etc.) en tableau
            separate_signature: true           # signature dans un bloc code sous le heading
            line_length: 88                    # wrap propre de la signature
            show_source: false                 # (optionnel) masque le lien "Source"
            merge_init_into_class: true        # doc de __init__ fusionnée dans la classe
            # petits plus possibles :
            # show_submodules: false
            # filters: ["!^_"]                 # cache membres privés
