site_name: NPBlender
site_description: "NumPy-based geometry for Blender"
site_author: "Alain Bernard"
repo_url: https://github.com/al1brn/npblender

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - content.code.copy

nav:
  - Home: index.md
  - Reference API:
      - Index: api/index.md
      - Mesh: api/mesh.md
      - Curve: api/curve.md
      - Cloud: api/cloud.md
      - Instances: api/instances.md
      - Meshes: api/meshes.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.details


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["."]
          import:
            mock:
              - bpy
              - bmesh
              - mathutils
          options:
            docstring_style: numpy             
            docstring_section_style: table     # sections (Arguments, Returns, etc.) en tableau
            separate_signature: true           # signature dans un bloc code sous le heading
            line_length: 88                    # wrap propre de la signature
            show_source: false                 # (optionnel) masque le lien "Source"
            merge_init_into_class: true        # doc de __init__ fusionnée dans la classe
            show_submodules: false
            show_private_members: false        # cache _membre
            show_special_members: false        # cache __dunder__
            show_undocumented_members: false   # évite d’afficher sans docstring
            filters:
              - "!^_"            # sécurité : exclut tout ce qui commence par _
              - "!^__.*__$"      # exclut __dunder__
            show_root_heading: true        # <— H1 = nom de l’objet (sert de “header” avec la docstring de classe)
            show_root_full_path: false     # <-- show only "Vertex" instead of "npblender.Vertex"
            heading_level: 1               # <— niveau de titre pour la racine
            members_order: alphabetical    # <— ordre alphabétique des méthodes/membres

  - autorefs





