__all__ = ["SYMBOLS", "SQRT_CHAR", "SIGMA_CHAR", "INTEGRAL_CHAR"]


# ====================================================================================================
# LaTeX symbols

SYMBOLS = {
    'Alpha'     : 'A',
    'alpha'     : 'α',
    'Beta'      : 'B',
    'beta'      : 'β',
    'Gamma'     : 'Γ',
    'gamma'     : 'γ',
    'Delta'     : 'Δ',
    'delta'     : 'δ',
    'Epsilon'   : 'E',
    'epsilon'   : 'ϵ',
    'varepsilon': 'ε',
    'Zeta'      : 'Z',
    'zeta'      : 'ζ',
    'Eta'       : 'H',
    'eta'       : 'η',
    'Theta'     : 'Θ',
    'theta'     : 'θ',
    'vartheta'  : 'ϑ',
    'Iota'      : 'I',
    'iota'      : 'ι',
    'Kappa'     : 'K',
    'kappa'     : 'κ',
    'varkappa'  : 'ϰ',
    'Lambda'    : 'Λ',
    'lambda'    : 'λ',
    'Mu'        : 'M',
    'mu'        : 'μ',
    'Nu'        : 'N',
    'nu'        : 'ν',
    'Xi'        : 'Ξ',
    'xi'        : 'ξ',
    'Omicron'   : 'O',
    'omicron'   : 'o',
    'Pi'        : 'Π',
    'pi'        : 'π',
    'varpi'     : 'π',
    'Rho'       : 'P',
    'rho'       : 'ρ',
    'varrho'    : 'ϱ',
    'Sigma'     : 'Σ',
    'sigma'     : 'σ',
    'varsigma'  : 'ς',
    'Tau'       : 'T',
    'tau'       : 'τ',
    'Upsilon'   : 'Υ',
    'upsilon'   : 'υ',
    'Phi'       : 'Φ',
    'phi'       : 'ϕ',
    'varphi'    : 'φ',
    'Chi'       : 'X',
    'chi'       : 'χ',
    'Psi'       : 'Ψ',
    'psi'       : 'ψ',
    'Omega'     : 'Ω',
    'omega'     : 'ω',

    'geq'       : '≥',
    'geqslant'  : '⩾',
    'gg'        : '≫',
    'ggg'       : '⋙',
    'leq'       : '≤',
    'leqslant'  : '⩽',
    'll'        : '≪',
    'lll'       : '⋘',
    'ngeq'      : '≱',
    'ngeqslant' : '⪈',
    'ngtr'      : '≯',
    'nleq'      : '≰',
    'nleqslant' : '⪇',
    'nless'     : '≮',
    'notsubset' : '⊄',
    'notsupset' : '⊅',
    'nprec'     : '⊀',
    'npreceq'   : '⋠',
    'nsubseteq' : '⊈',
    'nsucc'     : '⊁',
    'nsucceq'   : '⋡',
    'nsupseteq' : '⊉',
    'prec'      : '≺',
    'preceq'    : '⪯',
    'sqsubset'  : '⊏',
    'sqsubseteq' : '⊑',
    'sqsupset'  : '⊐',
    'sqsupseteq' : '⊒',
    'subset'    : '⊂',
    'subseteq'  : '⊆',
    'succ'      : '≻',
    'succeq'    : '⪰',
    'supset'    : '⊃',
    'supseteq'  : '⊇',

    'doteq'     : '≐',
    'equiv'     : '≡',
    'approx'    : '≈',
    'cong'      : '≅',
    'simeq'     : '≃',
    'sim'       : '∼',
    'propto'    : '∝',
    'neq'       : '≠',
    'neq'       : '≠',

    'times'     : '×',
    'pm'        : '±',
    'div'       : '÷',

    'exists'    : '∃',
    'nexists'   : '∄',
    'forall'    : '∀',
    'neg'       : '¬',
    'lor'       : '∨',
    'land'      : '∧',
    'top'       : '⊤',
    'bot'       : '⊥',

    #'{'         : '{',
    '|'         : '‖',
    'langle'    : '⟨',
    'rangle'    : '⟩',

    'rightarrow'     : '→',
    'to'             : '→',
    'longrightarrow' : '⟶',
    'mapsto'         : '↦',
    'longmapsto'     : '⟼',
    'leftarrow'      : '←',
    'gets'           : '←',
    'longleftarrow'  : '⟵',

    'implies'        : '⟹',
    'Longrightarrow' : '⟹',
    'Rightarrow'     : '⇒',
    'Longleftarrow'  : '⟸',
    'Leftarrow'      : '⇐',
    'iff'            : '⟺',
    'Leftrightarrow' : '⇔',

    'uparrow'       : '↑',
    'Uparrow'       : '⇑',
    'downarrow'     : '↓',
    'Downarrow'     : '⇓',
    'updownarrow'   : '↕',
    'Updownarrow'   : '⇕',

    'partial'       : '∂',
    'imath'         : 'ı',
    'Re'            : 'ℜ',
    'nabla'         : '∇',
    'eth'           : 'ð',
    'jmath'         : 'ȷ',
    'Im'            : 'ℑ',
    'hbar'          : 'ℏ',
    'ell'           : 'ℓ',
    'wp'            : '℘',
    'infty'         : '∞',
    'Box'           : '◻',
    }

