__all__ = ["SYMBOLS", "MATHBB"]


# ====================================================================================================
# LaTeX symbols


SYMBOLS = {
    'Alpha'     : 'Α',
    'alpha'     : 'α',
    'Beta'      : 'Β',
    'beta'      : 'β',
    'Gamma'     : 'Γ',
    'gamma'     : 'γ',
    'Delta'     : 'Δ',
    'delta'     : 'δ',
    'Epsilon'   : 'Ε',
    'epsilon'   : 'ϵ',
    'varepsilon': 'ε',
    'Zeta'      : 'Ζ',
    'zeta'      : 'ζ',
    'Eta'       : 'Η',
    'eta'       : 'η',
    'Theta'     : 'Θ',
    'theta'     : 'θ',
    'vartheta'  : 'ϑ',
    'Iota'      : 'Ι',
    'iota'      : 'ι',
    'Kappa'     : 'Κ',
    'kappa'     : 'κ',
    'varkappa'  : 'ϰ',
    'Lambda'    : 'Λ',
    'lambda'    : 'λ',
    'Mu'        : 'Μ',
    'mu'        : 'μ',
    'Nu'        : 'Ν',
    'nu'        : 'ν',
    'Xi'        : 'Ξ',
    'xi'        : 'ξ',
    'Omicron'   : 'Ο',
    'omicron'   : 'o',
    'Pi'        : 'Π',
    'pi'        : 'π',
    'varpi'     : 'ϖ',
    'Rho'       : 'Ρ',
    'rho'       : 'ρ',
    'varrho'    : 'ϱ',
    'Sigma'     : 'Σ',
    'sigma'     : 'σ',
    'varsigma'  : 'ς',
    'Tau'       : 'Τ',
    'tau'       : 'τ',
    'Upsilon'   : 'Υ',
    'upsilon'   : 'υ',
    'Phi'       : 'Φ',
    'phi'       : 'ϕ',
    'varphi'    : 'φ',
    'Chi'       : 'Χ',
    'chi'       : 'χ',
    'Psi'       : 'Ψ',
    'psi'       : 'ψ',
    'Omega'     : 'Ω',
    'omega'     : 'ω',

    'le'        : '≤', 
    'ge'        : '≥',

    'geq'       : '≥',
    'geqslant'  : '⩾',
    'gg'        : '≫',
    'ggg'       : '⋙',
    'leq'       : '≤',
    'leqslant'  : '⩽',
    'll'        : '≪',
    'lll'       : '⋘',
    'ngeq'      : '≱',
    'ngeqslant' : '⩾̸', #'⪈', 
    'ngtr'      : '≯',
    'nleq'      : '≰',
    'nleqslant' : '⩽̸', #'⪇', 
    'nless'     : '≮',
    'notsubset' : '⊄',
    'notsupset' : '⊅',
    'nprec'     : '⊀',
    'npreceq'   : '⋠',
    'nsubseteq' : '⊈',
    'nsucc'     : '⊁',
    'nsucceq'   : '⋡',
    'nsupseteq' : '⊉',
    'prec'      : '≺',
    'preceq'    : '⪯',
    'sqsubset'  : '⊏',
    'sqsubseteq' : '⊑',
    'sqsupset'  : '⊐',
    'sqsupseteq' : '⊒',
    'subset'    : '⊂',
    'subseteq'  : '⊆',
    'succ'      : '≻',
    'succeq'    : '⪰',
    'supset'    : '⊃',
    'supseteq'  : '⊇',

    'doteq'     : '≐',
    'equiv'     : '≡',
    'approx'    : '≈',
    'cong'      : '≅',
    'simeq'     : '≃',
    'sim'       : '∼',
    'propto'    : '∝',
    'neq'       : '≠',

    'times'     : '×',
    'pm'        : '±',
    'div'       : '÷',

    'exists'    : '∃',
    'nexists'   : '∄',
    'forall'    : '∀',
    'neg'       : '¬',
    'lor'       : '∨',
    'land'      : '∧',
    'top'       : '⊤',
    'bot'       : '⊥',
    'perp'      : '⟂',
    'in'        : '∈',
    'notin'     : '∉',

    'mid'       : '|',
    'Vert'      : '‖',
    '|'         : '‖',
    'langle'    : '⟨',
    'rangle'    : '⟩',

    'rightarrow'     : '→',
    'to'             : '→',
    'longrightarrow' : '⟶',
    'mapsto'         : '↦',
    'longmapsto'     : '⟼',
    'leftarrow'      : '←',
    'gets'           : '←',
    'longleftarrow'  : '⟵',

    'implies'        : '⟹',
    'Longrightarrow' : '⟹',
    'Rightarrow'     : '⇒',
    'Longleftarrow'  : '⟸',
    'Leftarrow'      : '⇐',
    'iff'            : '⟺',
    'Leftrightarrow' : '⇔',

    'leftrightarrow'    : '↔',
    'Longleftrightarrow': '⟺',
    'hookrightarrow'    : '↪',
    'hookleftarrow'     : '↩',

    'uparrow'       : '↑',
    'Uparrow'       : '⇑',
    'downarrow'     : '↓',
    'Downarrow'     : '⇓',
    'updownarrow'   : '↕',
    'Updownarrow'   : '⇕',

    'partial'       : '∂',
    'imath'         : 'ı',
    'Re'            : 'ℜ',
    'nabla'         : '∇',
    'eth'           : 'ð',
    'jmath'         : 'ȷ',
    'Im'            : 'ℑ',
    'hbar'          : 'ℏ',
    'ell'           : 'ℓ',
    'wp'            : '℘',
    'infty'         : '∞',
    'Box'           : '◻',

    'cdot'          : '·',          
    'circ'          : '∘',          

    'emptyset'      : '∅',     
    'varnothing'    : '∅',
    'setminus'      : '∖',
    'cap'           : '∩',
    'cup'           : '∪',
    'subsetneq'     : '⊊',
    'supsetneq'     : '⊋',
    'ni'            : '∋',

    'parallel'      : '∥',
    'lceil'         : '⌈',
    'rceil'         : '⌉',
    'lfloor'        : '⌊', 
    'rfloor'        : '⌋',

    'ldots'         : '…',
    'cdots'         : '⋯',

    'Pr'            : 'ℙ',
}

MATHBB = {
    'A': '𝔸',
    'B': '𝔹',
    'C': 'ℂ',
    'D': '𝔻',
    'E': '𝔼',
    'F': '𝔽',
    'G': '𝔾',
    'H': 'ℍ',
    'I': '𝕀',
    'J': '𝕁',
    'K': '𝕂',
    'L': '𝕃',
    'M': '𝕄',
    'N': 'ℕ',
    'O': '𝕆',
    'P': 'ℙ',
    'Q': 'ℚ',
    'R': 'ℝ',
    'S': '𝕊',
    'T': '𝕋',
    'U': '𝕌',
    'V': '𝕍',
    'W': '𝕎',
    'X': '𝕏',
    'Y': '𝕐',
    'Z': 'ℤ',

    'a': '𝕒',
    'b': '𝕓',
    'c': '𝕔',
    'd': '𝕕',
    'e': '𝕖',
    'f': '𝕗',
    'g': '𝕘',
    'h': '𝕙',
    'i': '𝕚',
    'j': '𝕛',
    'k': '𝕜',
    'l': '𝕝',
    'm': '𝕞',
    'n': '𝕟',
    'o': '𝕠',
    'p': '𝕡',
    'q': '𝕢',
    'r': '𝕣',
    's': '𝕤',
    't': '𝕥',
    'u': '𝕦',
    'v': '𝕧',
    'w': '𝕨',
    'x': '𝕩',
    'y': '𝕪',
    'z': '𝕫',
}
